import { Plan, VideoCampaign, VideoTask, AdPlacement, Announcement, Profile, Referral } from '../types/database';

export const INITIAL_PLANS: Plan[] = [
  {
    id: 'plan-1',
    name: 'Plan 1',
    description: 'Essential tier unlocking 7 daily sponsored tasks with consistent platform rewards.',
    price: 300,
    duration_days: 30,
    daily_task_limit: 7,
    reward_per_task: 8,
    daily_reward_limit: 56,
    min_withdrawal: 500,
    max_withdrawal: 10000,
    withdrawal_fee_pct: 2.5,
    is_active: true,
    display_order: 1,
    cta_text: 'Buy Plan 1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'plan-2',
    name: 'Plan 2',
    badge: 'POPULAR',
    description: 'Our most popular tier unlocking 12 daily tasks and elevated Rs. 10 task rewards.',
    price: 500,
    duration_days: 30,
    daily_task_limit: 12,
    reward_per_task: 10,
    daily_reward_limit: 120,
    min_withdrawal: 500,
    max_withdrawal: 15000,
    withdrawal_fee_pct: 2.5,
    is_active: true,
    display_order: 2,
    cta_text: 'Buy Plan 2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'plan-3',
    name: 'Plan 3',
    badge: 'VIP',
    description: 'Elite VIP tier unlocking 17 daily tasks and maximum Rs. 12 task disbursements.',
    price: 950,
    duration_days: 30,
    daily_task_limit: 17,
    reward_per_task: 12,
    daily_reward_limit: 204,
    min_withdrawal: 500,
    max_withdrawal: 25000,
    withdrawal_fee_pct: 2.0,
    is_active: true,
    display_order: 3,
    cta_text: 'Buy Plan 3',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_PLAN: Plan = INITIAL_PLANS[0];

export const INITIAL_CAMPAIGNS: VideoCampaign[] = [
  {
    id: 'camp-smarttech-01',
    name: 'SmartTech Home Automation 2026',
    sponsor_name: 'SmartTech Pakistan',
    description: 'Promoting energy-efficient smart home IoT sensors and automation hubs.',
    total_budget: 50000,
    spent_budget: 4200,
    reward_per_completion: 10,
    max_completions: 5000,
    current_completions: 420,
    status: 'active',
    start_date: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'camp-edulearn-02',
    name: 'EduLearn Web & AI Engineering Scholarships',
    sponsor_name: 'EduLearn Academy',
    description: 'Empowering students across South Asia with accredited technical skills.',
    total_budget: 35000,
    spent_budget: 2800,
    reward_per_completion: 12,
    max_completions: 2916,
    current_completions: 233,
    status: 'active',
    start_date: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'camp-greenenergy-03',
    name: 'SolarTech Green Inverter Initiative',
    sponsor_name: 'SolarTech Solutions',
    description: 'Residential solar net-metering and backup battery solutions.',
    total_budget: 40000,
    spent_budget: 1950,
    reward_per_completion: 15,
    max_completions: 2666,
    current_completions: 130,
    status: 'active',
    start_date: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];

export const INITIAL_VIDEOS: VideoTask[] = [
  {
    id: 'vid-smart-01',
    campaign_id: 'camp-smarttech-01',
    title: 'Smart Living 2026: IoT Automation Preview',
    description: 'Explore how smart home ecosystem controls lighting, security, and climate effortlessly from any smartphone.',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    duration_seconds: 30,
    reward_amount: 10,
    daily_limit: 500,
    per_user_limit: 1,
    status: 'active',
    category: 'Technology',
    sponsor_badge: 'SmartTech Certified',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vid-edu-02',
    campaign_id: 'camp-edulearn-02',
    title: 'Full-Stack Developer Career Roadmap 2026',
    description: 'A comprehensive walkthrough of modern cloud-native architectures, API security, and high-demand developer stacks.',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80',
    duration_seconds: 45,
    reward_amount: 12,
    daily_limit: 400,
    per_user_limit: 1,
    status: 'active',
    category: 'Education',
    sponsor_badge: 'EduLearn Sponsor',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vid-solar-03',
    campaign_id: 'camp-greenenergy-03',
    title: 'Zero-Electricity Bills with Hybrid Solar',
    description: 'Learn how smart net-metering and hybrid lithium inverters protect homes from load shedding and cut power bills.',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=600&auto=format&fit=crop&q=80',
    duration_seconds: 35,
    reward_amount: 15,
    daily_limit: 300,
    per_user_limit: 1,
    status: 'active',
    category: 'Clean Energy',
    sponsor_badge: 'SolarTech Verified',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vid-smart-04',
    campaign_id: 'camp-smarttech-01',
    title: 'Next-Gen Wireless Earbuds with ANC',
    description: 'Experience studio acoustics, ultra-low latency gaming mode, and 48-hour battery longevity.',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
    duration_seconds: 30,
    reward_amount: 10,
    daily_limit: 600,
    per_user_limit: 1,
    status: 'active',
    category: 'Gadgets',
    sponsor_badge: 'SmartTech Certified',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_ADS: AdPlacement[] = [
  {
    id: 'ad-cloud-01',
    title: 'Ultra-Fast NVMe Cloud VPS Hosting',
    placement: 'dashboard',
    image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    target_url: 'https://example.com/cloud-vps',
    sponsor_name: 'GlobalCloud Inc',
    impressions: 1240,
    clicks: 86,
    is_active: true,
  },
  {
    id: 'ad-dev-02',
    title: 'Supercharge Your Coding with Modern IDE Tools',
    placement: 'sidebar',
    image_url: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&auto=format&fit=crop&q=80',
    target_url: 'https://example.com/dev-tools',
    sponsor_name: 'DevCraft Studio',
    impressions: 890,
    clicks: 42,
    is_active: true,
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-01',
    title: 'Welcome to Earnzo Official Platform Launch!',
    content: 'Earnzo has officially launched. Activate your membership to watch brand-sponsored videos and earn verified platform rewards.',
    category: 'general',
    is_pinned: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ann-002',
    title: 'JazzCash & Easypaisa Instant Settlement Update',
    content: 'All verified withdrawal requests submitted before 4:00 PM are reviewed and approved on the same banking day.',
    category: 'payout',
    is_pinned: false,
    is_active: true,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const DEFAULT_ADMIN_PROFILE: Profile = {
  id: 'admin-usr-001',
  email: 'admin@earnzo.com',
  full_name: 'Lead Compliance Administrator',
  phone: '03001234567',
  role: 'admin',
  status: 'active',
  referral_code: 'ADMIN2026',
  created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEFAULT_USER_PROFILE: Profile = {
  id: 'user-usr-001',
  email: 'user@earnzo.com',
  full_name: 'Ali Raza',
  phone: '03219876543',
  role: 'user',
  status: 'active',
  referral_code: 'ALI789',
  created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_REFERRALS: Referral[] = [];

